Added support for building dev dockers from base spark kube docker im…
apache-spark-on-k8s/ansible pull request #4
Opened 2017-05-17 15:40 UTC by varunkatta

This change allows creating dev dockers quickly since it copies only the spark kubernetes core jar into an existing spark kubernetes docker image. These dev dockers are meant to be used mostly by developers to speed up their dev workflows.

2017-05-17 18:10 UTC, kimoonkim requested changes
Looks pretty good. Thanks for writing this PR!

I left a few minor suggestions. PTAL.

2017-05-17 18:10 UTC, kimoonkim commented on build_dev_dockers.yml
> +#      $ ansible-playbook -i TARGET-HOST build_dockers.yml [OPTIONS]...
s/build_dockers/build_dev_dockers/

2017-05-17 18:10 UTC, kimoonkim commented on build_dev_dockers.yml
> +# $ ansible-playbook -i localhost, build_dockers.yml -c local
Ditto.

2017-05-17 18:10 UTC, kimoonkim commented on build_dev_dockers.yml
> +                -t {{ docker_registry }}/spark-{{ item }}:{{ docker_tag }}  \
s/docker_tag/dev_docker_tag/ so that settings file can specify tags for base image and child image separately.

2017-05-17 18:10 UTC, kimoonkim commented on vars/settings.yml.template
> +# docker_base_image: spark-kube:latest
s/docker_base/dev_docker_base/ to be clear.

2017-05-23 20:02 UTC, varunkatta commented on build_dev_dockers.yml
> +#      $ ansible-playbook -i TARGET-HOST build_dockers.yml [OPTIONS]...
done.

2017-05-23 20:02 UTC, varunkatta commented on build_dev_dockers.yml
> +# $ ansible-playbook -i localhost, build_dockers.yml -c local
done

2017-05-23 20:03 UTC, varunkatta commented on build_dev_dockers.yml
> +                -t {{ docker_registry }}/spark-{{ item }}:{{ docker_tag }}  \
done

2017-05-23 20:03 UTC, varunkatta commented on vars/settings.yml.template
> +# docker_base_image: spark-kube:latest
done.

2017-05-23 20:27 UTC, kimoonkim requested changes
One more nit, then I think we're good to merge.

2017-05-23 20:27 UTC, kimoonkim commented on vars/settings.yml.template
> +# Optional. Base image to be used to build dev driver and executor dockers.
We need an entry for dev_docker_tag in this file?

2017-05-23 22:19 UTC, kimoonkim approved these changes

2017-05-23 22:19 UTC, kimoonkim commented
Thanks for this PR. @varunkatta 

Merging in.

2017-05-23 22:19 UTC, merged